



from typing import Literal

from pydantic import BaseModel, Field


class CourseMetadata(BaseModel):
    """
    Structured metadata generated by the Metadata Agent.

    This model is used as the agent's structured output before
    selecting a course template.
    """

    title: str = Field(
        ...,
        max_length=200,
        description="Name of the course.",
    )

    headline: str = Field(
        ...,
        max_length=200,
        description="A concise one-sentence promise of what the learner will achieve.",
    )

    description: str = Field(
        ...,
        description="A 3-6 sentence description explaining the course scope and expected outcomes.",
    )

    objectives: list[str] = Field(
        ...,
        min_length=1,
        description="List of learning objectives.",
    )

    prerequisites: list[str] = Field(
        default_factory=list,
        description="Knowledge or skills required before taking the course.",
    )

    target_audiences: str = Field(
        ...,
        max_length=300,
        description="Description of the intended audience for this course.",
    )

    primary_category_title: str = Field(
        ...,
        description="Broad course category (e.g. Programming, Management, Language Learning).",
    )

    primary_subcategory_title: str = Field(
        ...,
        description="Specific subject within the category (e.g. Python, Agile Leadership, Spanish).",
    )

    duration: str = Field(
        ...,
        description="Estimated course duration (e.g. '4 hours', '6 weeks').",
    )

    language: Literal[
        "English",
        "Spanish",
        "French",
        "Arabic",
    ] = Field(
        default="English",
        description="Language of instruction.",
    )