### Validation of metadata  

#Responsibilities:
#- Validate the metadata generated by the agent


#calling the pidantic format model of metadata course
from app.agents.metadata.models import CourseMetadata

#fuction to validate metadata 
def parse_metadata(data: dict) -> CourseMetadata:

    try:
        return CourseMetadata.model_validate(data)

    #rais the exaption hihihi
    except Exception as e:
        raise ValueError(f"Invalid metadata: {e}") from e