### Validation of metadata  

#Responsibilities:
#- Validate the metadata generated by the agent


#calling the pidantic format model of metadata course
from app.agents.metadata.models import CourseMetadata
from app.utils.logger import log_message

#fuction to validate metadata 
def parse_metadata(data: dict) -> CourseMetadata:
    with log_message("METADATA_PARSER", "#00B8D9", "Validating course metadata structure"):
        try:
            print("Validating course metadata structure ")
            return CourseMetadata.model_validate(data)
            
        #rais the exaption hihihi
        except Exception as e:
            raise ValueError(f"Invalid metadata: {e}") from e